iterations: 3

distance: 'lev'  # Choose: real, lev, adj, path, nasbot

threads: 16

fullKnas: False  # completely deterministic or not

kScheduler:
  type: "geometric"  # Choose: linear, geometric, manual
  first: 400  # can be set to -c: such that maxVal is size/c
  last: 20  # can be set to -c: such that mivVal is size/c
  manual: []

mScheduler:
  type: "manual"
  first: 3  # can be set to -c
  last: 1  # can be set to -c
  manual: [10,10,10]

qScheduler:
  type: "linear"
  first: 30  # can be set to -c, not used in case of geometric
  ratio: 1.5
  manual: []

